// Autogenerated main.js file

var director;

//------------------------------------------------------------------
//
// Main entry point - JSB
//
//------------------------------------------------------------------
if (cc.config.platform !== "browser") {

    // jsb specific
    require("jsb_constants.js");
    require("resources-jsb.js");

    // load game files
    require("Bomb.js");
    require("Coin.js");
    require("Dragon.js");
    require("EndCoin.js");
    require("Explosion.js");
    require("GameScene.js");
    require("Level.js");
    require("MainMenuScene.js");

    function main() {
        var scene = cc.BuilderReader.loadAsScene("MainMenuScene.ccbi");
        director = cc.Director.getInstance();

        gWinSize = cc.Director.getInstance().getWinSize();
        if (gWinSize.width <= 320)
            gScaleFactor = 1;
        else
            gScaleFactor = 2;

        var runningScene = director.getRunningScene();
        if (runningScene === null)
            director.runWithScene(scene);
        else
            director.replaceScene(scene);
    }

    main();
}

//------------------------------------------------------------------
//
// Main entry point - html5
//
//------------------------------------------------------------------
var CocosDragonScene = cc.Scene.extend({
    ctor:function () {
        this._super();
        //these variables will be declared as global variable
        audioEngine = cc.AudioEngine.getInstance();
        director = cc.Director.getInstance();

        gWinSize = cc.Director.getInstance().getWinSize();
        if (gWinSize.width <= 320)
            gScaleFactor = 1;
        else
            gScaleFactor = 2;

        var node = cc.BuilderReader.load("MainMenuScene.ccbi");

        this.addChild(node);
        this.setPosition(cc.p(0, 0));
    }
});

