// Autogenerated main.js file

require("jsb_constants.js");

require("Bomb.js");
require("Coin.js");
require("Dragon.js");
require("EndCoin.js");
require("Explosion.js");
require("GameScene.js");
require("Level.js");
require("MainMenuScene.js");
require("resources-html5.js");
require("resources-jsb.js");


function main()
{
	var director = cc.Director.getInstance();
    var scene = cc.BuilderReader.loadAsScene("MainMenuScene");
    var runningScene = director.getRunningScene();
    if (runningScene === null) director.runWithScene(scene);
    else director.replaceScene(scene);
}
main();